### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by bs-jena** [foliant-docs/foliant#49]
Trying to install Foliant on Xubuntu 18.04: Instead of retrieving the current (?) v1.0.9, pip collects 1.0.4, and then states an exception:

```
Collecting foliant
  Downloading https://files.pythonhosted.org/packages/2e/a3/cc4ef9eb194d5358e599b156857b495577c920e36e0b81d10e0fdf5a5806/foliant-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-T6DdDX/foliant/setup.py", line 13, in <module>
        except FileNotFoundError:
    NameError: name 'FileNotFoundError' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-T6DdDX/foliant/
```

**Comment by bs-jena** [comment]
Solved, there was a missing dependency.
