### ISSUE TITLE
Plantuml doesn't work in Docker mode.

### ISSUE THREAD

**Issue by arisc097** [foliant-docs/foliant#52]
I am using the docker approach. 

`2019-10-13 03:00:09,191 |              flt.cfg |  WARNING | Working in backward compatibility mode. To get rid of this warning, enable the escape_code config option
2019-10-13 03:00:09,223 |  flt.mkdocs.plantuml |    ERROR | Command 'plantuml .diagramscache/plantuml/0b281caf0bed2faae37fe21cf4015080.diag' returned non-zero exit status 127.
2019-10-13 03:00:09,225 |           flt.mkdocs |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/foliant/preprocessors/plantuml.py", line 117, in _process_plantuml
    run(command, shell=True, check=True, stdout=PIPE, stderr=STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'plantuml .diagramscache/plantuml/0b281caf0bed2faae37fe21cf4015080.diag' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

**Dockerfile:**
`FROM foliant/foliant
# If you plan to bake PDFs, uncomment this line and comment the line above:
# FROM foliant/foliant:pandoc

RUN pip3 install foliantcontrib.admonitions
RUN pip3 install foliantcontrib.badges
RUN pip3 install foliantcontrib.blockdiag
RUN pip3 install foliantcontrib.glossary
RUN pip3 install foliantcontrib.graphviz
RUN pip3 install foliantcontrib.imagemagick
RUN pip3 install foliantcontrib.plantuml
RUN pip3 install foliantcontrib.csvtables
COPY requirements.txt .
RUN pip3 install -r requirements.txt
`
**foliant.yml:**
`title: Hello Foliant

chapters:
  - index.md

preprocessors:
  - admonitions
  - badges
  - blockdiag
  - csvtables
  - glossary
  - graphviz
  - imagemagick
  - plantuml:
      parse_raw: true
`

**$ docker-compose build --force-rm**
[1570941564.log](https://github.com/foliant-docs/foliant/files/3721429/1570941564.log)

`
Building hello-foliant
Step 1/11 : FROM foliant/foliant
 ---> a4df1ec12308
Step 2/11 : RUN pip3 install foliantcontrib.admonitions
 ---> Using cache
 ---> d7cb3f6539e0
Step 3/11 : RUN pip3 install foliantcontrib.badges
 ---> Using cache
 ---> 3fca05075b08
Step 4/11 : RUN pip3 install foliantcontrib.blockdiag
 ---> Using cache
 ---> 8a90d5abd1a2
Step 5/11 : RUN pip3 install foliantcontrib.glossary
 ---> Using cache
 ---> 6e51980acbf7
Step 6/11 : RUN pip3 install foliantcontrib.graphviz
 ---> Using cache
 ---> ddf91cb4b8c5
Step 7/11 : RUN pip3 install foliantcontrib.imagemagick
 ---> Using cache
 ---> ed7a0562ada1
Step 8/11 : RUN pip3 install foliantcontrib.plantuml
 ---> Using cache
 ---> 86771dacac7f
Step 9/11 : RUN pip3 install foliantcontrib.csvtables
 ---> Using cache
 ---> 5b5d58d4e570
Step 10/11 : COPY requirements.txt .
 ---> Using cache
 ---> aba452c55f77
Step 11/11 : RUN pip3 install -r requirements.txt
 ---> Using cache
 ---> f905bba788e0
Successfully built f905bba788e0
Successfully tagged hello-foliant_hello-foliant:latest
`

**$ docker-compose run --rm hello-foliant make site**
`
Parsing config... Done
Applying preprocessor admonitions... Done
Applying preprocessor badges... Done
Applying preprocessor blockdiag... Done
Applying preprocessor csvtables... Done
Applying preprocessor glossary... Done
Applying preprocessor graphviz... WARNING: [hello.md] Processing of GraphViz diagram failed.

Done
Applying preprocessor imagemagick... Done
Applying preprocessor plantuml... Failed to apply preprocessor plantuml: Failed: /bin/sh: 1: plantuml: not found

Applying preprocessor mkdocs... Done
Applying preprocessor _unescape... Done
Making site with MkDocs... Done
────────────────────
Result: Hello_Foliant-2019-10-13.mkdocs
`

**Log:**
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/foliant/backends/base.py", line 72, in apply_preprocessor
    preprocessor_options
  File "/usr/local/lib/python3.7/dist-packages/foliant/preprocessors/plantuml.py", line 200, in apply
    processed_content = self.process_plantuml(content)
  File "/usr/local/lib/python3.7/dist-packages/foliant/preprocessors/plantuml.py", line 185, in process_plantuml
    processed = self.pattern.sub(_sub, content)
  File "/usr/local/lib/python3.7/dist-packages/foliant/preprocessors/plantuml.py", line 169, in _sub
    diagram.group('body')
  File "/usr/local/lib/python3.7/dist-packages/foliant/preprocessors/plantuml.py", line 146, in _process_plantuml
    raise RuntimeError(f'Failed: {exception.output.decode()}')
RuntimeError: Failed: /bin/sh: 1: plantuml: not found`

**Comment by anorm** [comment]
You need to have your `Dockerfile` install `plantuml` as well. The `foliantcontrib.plantuml` installed in step 9 is the foliant plugin which expects `plantuml` to be reachable by the `PATH`.

You can solve this issue by either installing `plantuml` or by basing your `Dockerfile` on the `foliant/foliant:full` tag instead of the `latest` tag. The latter is the easier option:

Replace line 1 in your `Dockerfile` with:
```
FROM foliant/foliant:full
```

Also, since the `full` tag contains all the official contribs, you can remove all the lines starting with `RUN pip3 install foliantcontrib` from you Dockerfile.
